module.exports = {
  USA: { name: "США", neighbors: ["CAN", "MEX"], resources: { food: 4, metal: 5, energy: 6 }, x: 120, y: 100 },
  CAN: { name: "Канада", neighbors: ["USA"], resources: { food: 2, metal: 6, energy: 4 }, x: 120, y: 60 },
  MEX: { name: "Мексика", neighbors: ["USA"], resources: { food: 5, metal: 3, energy: 3 }, x: 120, y: 150 },
  BRA: { name: "Бразилия", neighbors: ["ARG", "PER", "COL"], resources: { food: 6, metal: 4, energy: 3 }, x: 200, y: 250 },
  ARG: { name: "Аргентина", neighbors: ["BRA", "CHL"], resources: { food: 5, metal: 3, energy: 2 }, x: 200, y: 320 },
  RUS: { name: "Россия", neighbors: ["NOR", "FIN", "UKR", "KAZ", "CHN", "MNG"], resources: { food: 3, metal: 6, energy: 7 }, x: 420, y: 80 },
  CHN: { name: "Китай", neighbors: ["RUS", "MNG", "KAZ", "IND", "LAO", "VNM"], resources: { food: 6, metal: 5, energy: 4 }, x: 500, y: 180 },
  IND: { name: "Индия", neighbors: ["CHN", "PAK", "BGD", "MMR"], resources: { food: 7, metal: 3, energy: 3 }, x: 480, y: 240 },
  PAK: { name: "Пакистан", neighbors: ["IND", "AFG", "IRN"], resources: { food: 4, metal: 4, energy: 3 }, x: 440, y: 230 },
  AFG: { name: "Афганистан", neighbors: ["PAK", "IRN", "TKM", "UZB", "TJK", "CHN"], resources: { food: 2, metal: 3, energy: 2 }, x: 460, y: 200 },
  IRN: { name: "Иран", neighbors: ["PAK", "AFG", "IRQ", "TUR"], resources: { food: 3, metal: 5, energy: 6 }, x: 420, y: 210 },
  IRQ: { name: "Ирак", neighbors: ["IRN", "TUR", "SYR", "JOR", "KWT", "SAU"], resources: { food: 2, metal: 2, energy: 8 }, x: 400, y: 230 },
  SAU: { name: "Сауд. Аравия", neighbors: ["IRQ", "JOR", "YEM", "OMN", "QAT", "ARE"], resources: { food: 1, metal: 2, energy: 10 }, x: 410, y: 260 },
  EGY: { name: "Египет", neighbors: ["LBY", "SDN", "ISR"], resources: { food: 3, metal: 2, energy: 4 }, x: 360, y: 250 },
  FRA: { name: "Франция", neighbors: ["ESP", "DEU", "ITA", "BEL"], resources: { food: 4, metal: 4, energy: 5 }, x: 300, y: 140 },
  DEU: { name: "Германия", neighbors: ["FRA", "POL", "CZE", "AUT", "CHE", "NLD", "BEL"], resources: { food: 3, metal: 6, energy: 5 }, x: 320, y: 130 },
  ITA: { name: "Италия", neighbors: ["FRA", "AUT", "SVN"], resources: { food: 5, metal: 3, energy: 4 }, x: 330, y: 160 },
  ESP: { name: "Испания", neighbors: ["FRA", "PRT"], resources: { food: 5, metal: 3, energy: 3 }, x: 280, y: 160 },
  TUR: { name: "Турция", neighbors: ["GRC", "BGR", "GEO", "ARM", "IRN", "IRQ", "SYR"], resources: { food: 4, metal: 4, energy: 5 }, x: 380, y: 180 },
  JPN: { name: "Япония", neighbors: [], resources: { food: 3, metal: 2, energy: 6 }, x: 580, y: 140 },
  KOR: { name: "Корея", neighbors: ["PRK"], resources: { food: 3, metal: 4, energy: 5 }, x: 550, y: 160 },
  PRK: { name: "КНДР", neighbors: ["KOR", "CHN"], resources: { food: 2, metal: 3, energy: 3 }, x: 540, y: 150 },
  AUS: { name: "Австралия", neighbors: [], resources: { food: 4, metal: 7, energy: 5 }, x: 600, y: 300 },
  ZAF: { name: "ЮАР", neighbors: ["NAM", "ZMB", "MOZ"], resources: { food: 4, metal: 6, energy: 3 }, x: 380, y: 340 },
  NGA: { name: "Нигерия", neighbors: ["NER", "TCD", "CMR", "BEN"], resources: { food: 6, metal: 3, energy: 5 }, x: 320, y: 280 },
  IDN: { name: "Индонезия", neighbors: [], resources: { food: 6, metal: 4, energy: 4 }, x: 560, y: 260 },
  UKR: { name: "Украина", neighbors: ["RUS", "BLR", "POL", "ROU", "MDA"], resources: { food: 5, metal: 4, energy: 3 }, x: 360, y: 120 },
  POL: { name: "Польша", neighbors: ["DEU", "CZE", "SVK", "UKR", "LTU", "BLR"], resources: { food: 4, metal: 4, energy: 4 }, x: 340, y: 110 },
  KAZ: { name: "Казахстан", neighbors: ["RUS", "UZB", "KGZ", "CHN"], resources: { food: 2, metal: 6, energy: 6 }, x: 460, y: 140 },
  UZB: { name: "Узбекистан", neighbors: ["KAZ", "TKM", "AFG", "TJK"], resources: { food: 3, metal: 4, energy: 3 }, x: 480, y: 180 }
};